Add some rudimentary error checking and syntax printout, allow either instance name or instance ID to be used

diff --git a/ssm-ssh b/ssm-ssh
--- a/ssm-ssh
+++ b/ssm-ssh
@@ -1,10 +1,51 @@
 #!/bin/bash
 
-instance_name=$1
-port_number=$2
+if [ -z $* ]
+then
+  echo "Syntax:"
+  echo "  ssm-ssh <options> <args>"
+  echo "    Options:"
+  echo "      -n (optional): AWS instance tag name"
+  echo "      -i (optional): AWS instance ID"
+  echo "      Either -n or -i must be specified"
+  echo "    Arguments:"
+  echo "      port (optional, default 22)"
+  exit 0
+fi
 
-# find the instance ID based on Tag Name
-INSTANCE_ID=$(aws-resolve-host $instance_name)
+INSTANCE_NAME=""
+INSTANCE_ID=""
+
+while getopts "n:i:" opt; do
+  case ${opt} in
+    n) INSTANCE_NAME=${OPTARG};;
+    i) INSTANCE_ID=${OPTARG};;
+  esac
+done
+
+if [ -z $INSTANCE_NAME ] && [ -z $INSTANCE_ID ]
+then
+  echo "Must pass instance name with -n or instance id with -i"
+  exit 2
+fi
+
+shift $((OPTIND -1))
+
+if [ -z $INSTANCE_ID ]
+  then
+  # find the instance ID based on Tag Name
+  INSTANCE_ID=$(aws-resolve-host $INSTANCE_NAME)
+
+  exit_code=$?
+
+  if [ $exit_code -eq 1 ]
+  then
+    echo "Unable to resolve AWS host by tag name: $INSTANCE_NAME"
+    exit $exit_code
+  fi
+fi
+
+port_number=${1:-22}
 
 # create the session
 aws ssm start-session --target $INSTANCE_ID \
